### ISSUE TITLE
Module build failed: Error: Unexpected "space" found

### ISSUE THREAD

**Issue by hujb2000** [webpack-contrib/css-loader#250] opened 2016-04-01 02:31 UTC
css-loader version: 0.23.1 

ERROR in ../~/css-loader!./css/index.css
Module build failed: Error: Unexpected "space" found.
    at new error (/usr/src/app/node_modules/css-loader/node_modules/cssnano/node_modules/postcss-minify-selectors/node_modules/postcss-selector-parser/dist/processor.js:27:23)
    at Parser.error (/usr/src/app/node_modules/css-loader/node_modules/cssnano/node_modules/postcss-minify-selectors/node_modules/postcss-selector-parser/dist/parser.js:212:15)
    at Parser.pseudo (/usr/src/app/node_modules/css-loader/node_modules/cssnano/node_modules/postcss-minify-selectors/node_modules/postcss-selector-parser/dist/parser.js:320:18)
    at Parser.parse (/usr/src/app/node_modules/css-loader/node_modules/cssnano/node_modules/postcss-minify-selectors/node_modules/postcss-selector-parser/dist/parser.js:502:22)
    at Parser.loop (/usr/src/app/node_modules/css-loader/node_modules/cssnano/node_modules/postcss-minify-selectors/node_modules/postcss-selector-parser/dist/parser.js:470:18)
    at new Parser (/usr/src/app/node_modules/css-loader/node_modules/cssnano/node_modules/postcss-minify-selectors/node_modules/postcss-selector-parser/dist/parser.js:89:21)
    at Processor.process (/usr/src/app/node_modules/css-loader/node_modules/cssnano/node_modules/postcss-minify-selectors/node_modules/postcss-selector-parser/dist/processor.js:24:21)
    at getParsed (/usr/src/app/node_modules/css-loader/node_modules/cssnano/node_modules/postcss-minify-selectors/dist/index.js:28:59)
    at optimise (/usr/src/app/node_modules/css-loader/node_modules/cssnano/node_modules/postcss-minify-selectors/dist/index.js:38:21)
    at /usr/src/app/node_modules/css-loader/node_modules/postcss/lib/container.js:110:28
    at /usr/src/app/node_modules/css-loader/node_modules/postcss/lib/container.js:73:26
    at Root.each (/usr/src/app/node_modules/css-loader/node_modules/postcss/lib/container.js:60:22)
    at Root.walk (/usr/src/app/node_modules/css-loader/node_modules/postcss/lib/container.js:72:21)
    at Root.walkRules (/usr/src/app/node_modules/css-loader/node_modules/postcss/lib/container.js:108:25)
    at /usr/src/app/node_modules/css-loader/node_modules/cssnano/node_modules/postcss-minify-selectors/dist/index.js:107:20
    at LazyResult.run (/usr/src/app/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:206:20)
    at /usr/src/app/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:120:37
    at LazyResult.asyncTick (/usr/src/app/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:134:15)
    at /usr/src/app/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:132:27
    at LazyResult.asyncTick (/usr/src/app/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:134:15)
    at /usr/src/app/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:132:27
    at LazyResult.asyncTick (/usr/src/app/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:134:15)
    at /usr/src/app/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:132:27
    at LazyResult.asyncTick (/usr/src/app/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:134:15)
    at /usr/src/app/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:132:27
    at LazyResult.asyncTick (/usr/src/app/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:134:15)
    at /usr/src/app/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:132:27
    at LazyResult.asyncTick (/usr/src/app/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:134:15)
    at /usr/src/app/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:132:27
    at LazyResult.asyncTick (/usr/src/app/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:134:15)
 @ ./css/index.css 4:14-79

Can you help me solve this bug?

**Comment by helloyou2012** [comment] 2016-04-01 02:46
Plz view the log: `@ ./css/index.css 4:14-79`

**Comment by LeZuse** [comment] 2016-04-12 10:39
@hujb2000 Have you fixed the issue? I am having the same problem here. Seems like some kind of PostCSS misconfiguration.

**Comment by loopmode** [comment] 2016-04-17 14:48
I have similar symptoms, and in my case it seems to be caused by a function definition in my scss.

    $clr-success: $green;

    $light-gray-2: #E4E4E4;
    $colors: (
        globalBackground: $light-gray-2,
        ....
    );
    // usage example: body { background: color(globalBackground); }
    // problematic block starts here
    @function color($key) {
        @if map-has-key($colors, $key) {
            @return map-get($colors, $key);
        }
        @warn "Unknown `#{$key}` in $colors.";
        @return null;
    }
    // poblematic blockends here
The error is thrown in `postcss-selector-parser/dist/parser.js`, `Parser.prototype.pseudo = function pseudo() {}`,

    if (this.currToken[0] === 'word') { ... } else { this.error('Unexpected "' + this.currToken[0] + '" found.'); }

curToken[0] is actually "space"... somehow..  and when i remove that @function definition in my scss, the error is not thrown anymore.

(css-loader 0.21.0)

**Comment by LeZuse** [comment] 2016-04-17 21:19
We also managed to find the issue. The real problem here is that the original error message does not show up the the log, so the user has ho idea on what to fix. I our case it was invalid LESS-like comment in a postcss stylesheet.

**Comment by Norm-** [comment] 2016-09-29 13:20
@tj @seaneking

I ran into the same error. I am using stylus, extractText and postcss (via poststylus)

Bundling the css works when I'm in dev mode. The error appears only when I try to bundle a production version. The only difference between those two setups is the `UglifyJsPlugin`

I had a typo in my .styl file (tab instead of space). So stylus thought I was starting a new selector and split my nested block in the middle. Obviously, it lets me write whatever I want. It created something like;

```
.foo {
  color: white;
  margin: 0 auto;
}

border-radius {
  0.5rem;
}
```

That gets passed to postcss plugins afterwards. *That* throws the error (as mentioned above)

It's no plugin's bug. Just that they are too trusting of my human errors.

Thus, I solved it and learned to check my .styl files carefully for indentation in the future.

The fact remains that we need some kind of error reporting to track the issue. My thinking is; either stylus should warn when you mix tabs/spaces (which is valid but might be unintended) or poststylus should log out the chunk of CSS it had trouble parsing.

**Comment by monsterooo** [comment] 2017-01-20 09:46
i have same proble, because my syntax is error;
```
/*error*/
:global (
  #app {
    height: 100%;
  }
)
``` 
```
/*right*/
:global {
  #app {
    height: 100%;
  }
}
``` 
i hope cant help some people

**Comment by timhjellum** [comment] 2017-01-27 00:10
I removed all of the comments in the CSS files and this fixed the issue for me.

**Comment by nshoes** [comment] 2017-02-24 23:01
@timhjellum thanks! That worked for me 😆

**Comment by anwari32** [comment] 2017-03-11 05:02
Hello, I think I found the same thing. I tried the idea from @timhjellum but it didn't work. I also didn't get which css file that failed. 

Module build failed: Error: Unexpected "space" found.
    at new error (/some_folder/another_folder/myapp/node_modules/postcss-selector-parser/dist/processor.js:29:23)
    at Parser.error (/some_folder/another_folder/myapp/node_modules/postcss-selector-parser/dist/parser.js:234:15) etc.

It turned out that there were spaces in syntax like this `.grid: not(.no-bp) [class*=col-]`. Notice the space between ':' and "not". After I removed the space, the app could compile. Hope this helps.

**Comment by smacky197** [comment] 2017-06-09 10:55
not working bro @anwari32 i notice the spaces and after removing them it shows same error again

**Comment by evilebottnawi** [comment] 2017-06-09 11:44
@smacky197 can your provide minimal reproducible test repo?

**Comment by eldan-klarna** [comment] 2017-07-17 13:26
@monsterooo thanks!
for me it only worked like this:
:global #app {
  height: 100%;
}

**Comment by abimelex** [comment] 2017-11-30 14:34
For me it was just a forgotten semicolon at the end of a nested block. It worked in dev mode but failed during minification on production.
`
.className {
    padding: 3px;
    margin: 0 10px /*note the missing semicolon in this line*/

    subClass {
        margin: 0;
    }
}
`

**Comment by loopmode** [comment] 2017-11-30 14:42
I guess what we all would appreciate is better description of what went wrong, when it goes wrong..

**Comment by evilebottnawi** [comment] 2017-11-30 14:50
@abimelex known issue, need stable release `cssnano@4`

**Comment by hermeslm** [comment] 2018-01-21 02:26
This error is clearly a CSS error, but if you use many libs from third parties as was my case, finding it is like looking for a needle in a haystack, my solution was to go to the file: "node_modules/postcss-elector-arser/dist/processor.js" and on line 29 where the error is launched with a very generic message I just add to the error message the "selectors" variable that has the selectors that are be parsing:

original:
`Line 29:      throw new Error (e);`

Updated by:
`Line 29:       throw new Error (e + "in selectors:" + selectors);`

Using this way it is possible to see which CSS selectors have the error and correct it.

This was my solution to solve the problem, I hope it helps others because for me it was a waste of 2 days of hard work.

**Comment by jaredramirez** [comment] 2018-02-06 23:28
I just ran into this as well. My issue was:
```
@media screen and (min-width: 769px) {
    nav: hover { /* extra space on this line*/
        color: #313b44;
    }
}
```

**Comment by evilebottnawi** [comment] 2018-02-15 13:28
Out of scope `css-loader`, should be fixed in `cssnano`, seems need release stable `cssnano` version :+1:

**Closed** 2018-02-15 16:30 UTC
Labels: priority: 4 (important), semver: Patch, severity: 3 (broken), type: Bug
