### ISSUE TITLE
Can't import style when i add a option of "modules"

### ISSUE THREAD

**Issue by zhayes** [webpack-contrib/css-loader#1073] opened 2020-04-08 03:21 UTC
- Operating System: MacOs
- Node Version: 9.5.0
- NPM Version:6.1.0
- webpack Version:4.16.2
- css-loader Version:3.5.1

### Expected Behavior

I hope that the  the file of 'index.css' can be compiled by css-loader.

### Actual Behavior
I find that the file of 'index.css'  be not compiled by.

Below, I took some pictures

### Code

```js
{
                test: /\.css$/,
                exclude: /antd\.css/,
                use: [
                    'style-loader',
                    {
                        loader: 'css-loader',
                        options: {
                            modules: {
                                localIdentName: '[path][name]__[local]--[hash:base64:5]',
                            }
                        }
                    },
                    'postcss-loader'
                ]
            },
```

On browser, I have a finding that a file  of  ’index.css' is not imported

![image](https://user-images.githubusercontent.com/17758062/78740783-4519fc00-798a-11ea-84d8-90e63277c2cc.png)

![image](https://user-images.githubusercontent.com/17758062/78741049-e903a780-798a-11ea-9ebc-72225cfdf552.png)

![image](https://user-images.githubusercontent.com/17758062/78741025-d8ebc800-798a-11ea-96c2-ff281d5d7d17.png)

if i remove the option, it works.

**Comment by evilebottnawi** [comment] 2020-04-08 10:05
It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

Please fill all fields, I can't understand a problem, we don't remove your CSS

**Comment by evilebottnawi** [comment] 2020-04-08 10:06
Maybe the problem in https://github.com/webpack/webpack/blob/master/examples/side-effects/README.md, but you don't provide steps or reproducible test repo, so I can't help

**Comment by zhayes** [comment] 2020-04-09 03:39
> Maybe the problem in https://github.com/webpack/webpack/blob/master/examples/side-effects/README.md, but you don't provide steps or reproducible test repo, so I can't help

If i add the option of modules, the style file can't be compiled by css-loader.

**Comment by evilebottnawi** [comment] 2020-04-09 11:07
Please fill out the code normally, you can create minimum github reproducible test repo

**Comment by zhayes** [comment] 2020-04-11 07:07
> Please fill out the code normally, you can create minimum github reproducible test repo

[https://github.com/zhayes/zha-cli-template.](https://github.com/zhayes/zha-cli-template.)
npm start.

The style file  of  './src/components/Layout/index.css' can't be not compiled.

**Comment by zhayes** [comment] 2020-04-30 08:32
Can you solve my question? @evilebottnawi

**Comment by evilebottnawi** [comment] 2020-04-30 09:56
Yes, my recommendation:
1. Rename CSS files with modules to `*.modules.css`, i.e. `index.css` to `index.modules.css`
2. Put `declare module "*.modules.css";` in `global.d.ts` 
3. Change `import './index.css';` to `import './index.css';`
4. Change `<div className="logo" />` to ` <div className={ styles.logo } />`

All works fine.

**Closed by evilebottnawi** 2020-04-30 09:56 UTC
