### ISSUE TITLE
CssSyntaxError: postcss-modules-scope referenced class name "xyz" in composes not found

### ISSUE THREAD

**Issue by ahmed1490** [webpack-contrib/css-loader#290] opened 2016-06-22 12:37 UTC
Filename

```
@value icons: '../shared/icon.css';
@value typography: '../shared/typography.css';
@value colors: '../shared/colors.css';
@value medium as bp-medium, large as bp-large from "../shared/breakpoints.css";

.rating_star {
    composes: icon-size12 from icons;
}
```

error below

```
ERROR in ./~/css-loader?modules&importLoaders=1&localIdentName=[path]___[name]__[local]___[hash:base64:5]!./components/ArticleDetail/ArticleDetail.css
Module build failed: CssSyntaxError: postcss-modules-scope: /css-loader!/Users/aabbas/ui-wishlist/components/ArticleDetail/ArticleDetail.css:7:5: referenced class name "icon-size12" in composes not found
    at Input.error (/Users/aabbas/ui-wishlist/node_modules/postcss/lib/input.js:61:22)
    at Declaration.error (/Users/aabbas/ui-wishlist/node_modules/postcss/lib/node.js:74:38)
    at /Users/aabbas/ui-wishlist/node_modules/postcss-modules-scope/lib/index.js:125:24
    at Array.forEach (native)
    at /Users/aabbas/ui-wishlist/node_modules/postcss-modules-scope/lib/index.js:108:17
    at /Users/aabbas/ui-wishlist/node_modules/postcss/lib/container.js:100:28
    at /Users/aabbas/ui-wishlist/node_modules/postcss/lib/container.js:81:26
    at Rule.each (/Users/aabbas/ui-wishlist/node_modules/postcss/lib/container.js:68:22)
    at Rule.walk (/Users/aabbas/ui-wishlist/node_modules/postcss/lib/container.js:80:21)
    at Rule.walkDecls (/Users/aabbas/ui-wishlist/node_modules/postcss/lib/container.js:98:25)
 @ ./components/ArticleDetail/ArticleDetail.css 4:14-169 13:2-17:4 14:20-175
```

**Comment by OliverJAsh** [comment] 2017-05-26 13:16
I think this may have been fixed by https://github.com/webpack-contrib/css-loader/pull/534.

Can you try out 0.28.3 and confirm?

**Comment by evilebottnawi** [comment] 2018-02-13 16:18
Closing due to inactivity. Please test with latest version and feel free to reopen if still regressions. Thanks!

**Closed by evilebottnawi** 2018-02-13 16:18 UTC
