### ISSUE TITLE
@imports not resolving when css-modules enabled

### ISSUE THREAD

**Issue by edwinwright** [webpack-contrib/css-loader#436] opened 2017-03-02 09:17 UTC
I'm trying to import normalize.css from the `node_modules` directory. When I have the default configuration it works as expected.

```
@import "~normalize.css/normalize.css";
```

When I enable css-modules I get a webpack compilation error:

```
Module not found: Error: Can't resolve '~normalize.css/normalize.css'
```

Is this expected behaviour or a bug?

I'm using:
- css-loader: 0.26.2
- webpack: 2.2.1

**Comment by michael-ciniawsky** [comment] 2017-03-06 20:16
@edwinwright Only for `@imports` using `~` ?

1. webpack.config.js
2. Component which imports CSS (Modules)

Thx in advance 🙃

**Comment by edwinwright** [comment] 2017-03-07 10:28
@michael-ciniawsky Yes, since I logged this, I found that it does work without the `~` prefix.

It is confusing though. I wouldn't have thought that enabling the module would change the behaviour like this.

1. webpack.config.js
```
const { resolve } = require('path');
const webpack = require('webpack');

module.exports = {
  context: resolve(__dirname, './src'),
  entry: {
    app: [
      'babel-polyfill',
      'react-hot-loader/patch',
      'webpack-hot-middleware/client',
      './index.js',
    ],
  },
  output: {
    filename: '[name].bundle.js',
    path: resolve(__dirname, './dist'),
    publicPath: '/',
  },
  devtool: 'inline-source-map',
  module: {
    rules: [
      {
        test: /\.js$/,
        use: ['babel-loader'],
        exclude: [/node_modules/],
      },
      {
        test: /\.s?css$/,
        use: [
          'style-loader',
          {
            loader: 'css-loader',
            options: {
              modules: true,
              localIdentName: '[local]--[hash:base64:5]',
            },
          },
          'sass-loader',
        ],
      },
    ],
  },
  plugins: [
    new webpack.HotModuleReplacementPlugin(),
    new webpack.NamedModulesPlugin(),
  ],
};
```

2. App.css
```
@charset "utf-8";
@import "normalize.css/normalize.css";

* {
  box-sizing: border-box;
}
```

**Comment by michael-ciniawsky** [comment] 2017-03-07 16:39
> It is confusing though. I wouldn't have thought that enabling the module would change the behaviour like this.

Yeah :D, we need to take a serious look at the resolver, it should work like you expected 😛 

> `@charset "utf-8";`

Is this line mandatory for you atm, bc #355 and regardless of that does `@charset` work for you ?

**Comment by edwinwright** [comment] 2017-03-08 09:15
`@charset` is not mandatory for me at the moment, but I haven't noticed any problems with it so far.

**Comment by LinuCC** [comment] 2017-03-30 16:34
@edwinwright @michael-ciniawsky  isnt this a result of the request-behaviour used in modules?
The README says the following:

> `url()` URLs in block scoped (`:local .abc`) rules behave like requests in modules:
> 
> * `./file.png` instead of `file.png`
> * `module/file.png` instead of `~module/file.png`

I had the same issue, it seems kinda counterintuitive:

```SCSS
:global { * { background: url('~assets/my-asset.svg'); } } // works
```

```SCSS
:local { * { background: url('~assets/my-asset.svg'); } } // does not work
```

```SCSS
:local { * { background: url('assets/my-asset.svg'); } } // no tilde here but works
```

That is odd behaviour. 
Because of this resolving the actual URL is context-sensitive making global variables ala bootstrap-sass (e.g. `$styleguilde-asset-url` / `$bootstrap-font-url`) awkward to use.

**Comment by ipelekhan** [comment] 2017-07-21 15:42
Any update on this?

**Comment by lcsrinaldi** [comment] 2017-10-17 17:51
Any futher improvement on this issue?

**Comment by evilebottnawi** [comment] 2017-10-18 09:40
@lcsrinaldi please provide minimum reproducible test repo, thank you!

**Comment by lcsrinaldi** [comment] 2017-10-18 18:25
@evilebottnawi sorry, I don't know how to provide you with that. Isn't the issue already specified by other comments?

**Comment by lnhrdt** [comment] 2017-10-31 11:34
Hello @evilebottnawi! @jantimon produced a testable repo in #589. I see you commented there but the conversation stalled. Can you take another look?

**Comment by evilebottnawi** [comment] 2018-02-15 14:29
Close in favor https://github.com/webpack-contrib/css-loader/issues/589#issuecomment-365942989

**Closed by evilebottnawi** 2018-02-15 14:29 UTC
Labels: type: Bug
