### ISSUE TITLE
url with paths to directories bug

### ISSUE THREAD

**Issue by jmlopez-rod** [webpack-contrib/css-loader#322] opened 2016-08-28 07:36 UTC
When a url points to a directory the css loader fails since it doesn't know how to substitute it. This is weird but the guys at leaflet are using this in order to resolve paths with css. Would it be possible to simply leave the paths that the loader can't find untouched? At least a warning saying so?

Please see https://github.com/Leaflet/Leaflet/issues/4849 to see what the css contains and why it breaks the css loader. At the moment I can't make a leaflet bundle with their latest code due to this issue.

**Comment by rbilgil** [comment] 2016-09-27 14:11
It would be great if css-loader didn't fail hard here (especially as Leaflet have decided not to fix this issue). Due to this, we are unable to build any of our JS bundles without downgrading to Leaflet 1.0 RC1.

**Comment by jacobmischka** [comment] 2016-09-27 16:25
After about an hour of trying to get null-loader or noop-loader to work, I learned that IgnorePlugin was a thing and was able to workaround this issue with that.

```
const webpack = require('webpack');
const ignore = new webpack.IgnorePlugin(/images(\/)?$/, /leaflet/);

/* eslint-env node */
module.exports = {
...
	plugins: [ignore],
};
```

**Comment by jacobmischka** [comment] 2016-09-27 16:34
After over an hour of trying to get webpack to ignore this correctly I gave up and just disabled url() resolution in css-loader.

I thought I'd solved it with webpack.IgnorePlugin, but I didn't realize that css-loader would still break even if the webpack build finished without errors after ignoring the `images/` import.

**Comment by jcreamer898** [comment] 2016-09-27 19:26
sigh

**Comment by nikolauskrismer** [comment] 2016-09-27 19:53
anything new on this?
with leaflet-1.0.0 released today this will affect everyone using webpack and trying to update to latest leaflet

**Comment by jacobmischka** [comment] 2016-09-28 15:04
Even if css-loader didn't error out, it wouldn't copy all of the images anyway since they're not referenced in the css. I'm not really sure how or why leaflet set up the their css this way, but you'll either need to copy the images folder yourself or reference a CDN, I believe.

This definitely seems like a problem with leaflet's implementation, disappointing that they've considered it wontfix.

**Comment by evilebottnawi** [comment] 2018-02-13 16:24
Closing due to inactivity. Please test with latest version and feel free to reopen if still regressions. Thanks!

**Closed by evilebottnawi** 2018-02-13 16:24 UTC
