### ISSUE TITLE
css-loader 0.27.3 adds ~20kb more than 0.26.2 to the bundle. Is that correct?

### ISSUE THREAD

**Issue by julenr** [webpack-contrib/css-loader#467] opened 2017-03-26 02:06 UTC
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as your webpack version, Node.js version and Operating System.**

**Comment by michael-ciniawsky** [comment] 2017-03-26 11:01
Its because if the `Buffer` polyfill included for sourcemaps conversion and will be fixed soon :) Duplicate of #454

**Closed by michael-ciniawsky** 2017-03-26 11:01 UTC

**Comment by JackHowa** [comment] 2020-12-11 16:31
is it possible that I'm still seeing this issue with `css-loader@2.1.1 `? I'm seeing that Buffer package in unused js. and I do not have the suggestion in yet? 

```
    node: {
      Buffer: false
    },
```

https://github.com/webpack-contrib/css-loader/releases/tag/v2.1.1

**Comment by JackHowa** [comment] 2021-06-11 20:00
@michael-ciniawsky @julenr have you seen this with css-loader recently 


"webpack": "^4.32.2",
    "css-loader": "^2.1.1",


```
          {
            test: /\.s?[ac]ss$/i,
            use: [
              {
                loader: 'css-loader',
                options: {
                  url: false
                }
              }
            ]
          },
```
