### ISSUE TITLE
broken escaping

### ISSUE THREAD

**Issue by eeve** [webpack-contrib/css-loader#578] opened 2017-07-14 08:04 UTC
**What is the current behavior?**
 The escape symbol `\` was lost
```css
.grid            { display: flex; flex-wrap: wrap; }
.grid.\-top      { align-items: flex-start; }
.grid.\-middle   { align-items: center; }
.grid.\-bottom   { align-items: flex-end; }
```
=>

```css
.grid            { display: flex; flex-wrap: wrap; }\n.grid.-top      { align-items: flex-start; }\n.grid.-middle   { align-items: center; }\n.grid.-bottom   { align-items: flex-end; }\n
```

**What is the expected behavior?**
Keep the escape symbol `\`

https://github.com/eeve/test.v1

**Comment by evilebottnawi** [comment] 2017-07-14 16:37
@eeve btw, why your use `\` in `selectors`

**Comment by jschlieber** [comment] 2017-07-20 08:16
I'm running into the exact same issue. In my case escape sequences are used in Predix-UI CSS Modules, e.g:

https://github.com/PredixDev/px-spacing-design/blob/db32341b44fee68cace50d5d236306f768bbed26/_trumps.spacing.scss#L175-L181

So that basically means I can't use those `u-m+` and `u-m++` classes.

Any ideas for a quick workaround?

**Comment by evilebottnawi** [comment] 2017-07-20 12:31
@jschlieber unfortunately no, try to found and fix problem today

**Comment by jschlieber** [comment] 2017-07-26 05:34
@evilebottnawi Any news on this issue?

**Comment by evilebottnawi** [comment] 2017-07-26 12:13
@jschlieber I was on vacation, in the near future I will take care of this, thanks for waiting

**Comment by evilebottnawi** [comment] 2017-07-26 16:28
@jschlieber `u-m+` and `u-m++` invalid css classes (https://jigsaw.w3.org/css-validator/validator), your should use `u-m\+` and `u-m\+\+`

**Comment by evilebottnawi** [comment] 2017-07-26 16:36
@jschlieber also `.\-top {}` and `.-top {}` are valid class selectors and mean the same thing.

**Comment by evilebottnawi** [comment] 2017-07-26 17:11
Bug inside `postcss-modules-local-by-default` and `postcss-modules-scope`, they remove `\` character. But i wonder use case. 

@jschlieber `.u-m\+` and etc selectors work good (https://github.com/webpack-contrib/css-loader/pull/584).

@TrySound what do your think about this?

**Comment by jschlieber** [comment] 2017-07-27 09:47
@evilebottnawi Ok, but what you're telling me is that i can't define my css selector as:
```css
.u-m++{
  ...
}
```
and I'm totally fine with that. But still, if classes are defined like this
```css
.u-m\00002b{
  ...
}
```
as in the PredixUi CSS library (which btw is valid css). I can't use it like it is intended, e.g.
```html
<div class="u-m+">
  ...
</div>
```
because it ends up as
```css
.u-m00002b{
  ...
}
```
so I would have to use it like this
```html
<div class="u-m00002b">
  ...
</div>
```

**Comment by evilebottnawi** [comment] 2017-07-27 16:17
@jschlieber don't understand your. Your can use `.u-m\00002b` in your css and `css-loader` works fine. 
Input:
```css
.u-m\00002b {
    border: 10px solid black;
}
```

Output:
```css
.u-m\00002b {
  border: 10px solid black;
}
```

Just try to test in your project.
I agree what `css-loader` should not remove `\`, but it is happens only with selector where escaped is not necessary (example if your have `\.-top {}`, your can use `.-top {}`, because `\.-top {}` and `.-top {}` are mean the same thing).

**Comment by evilebottnawi** [comment] 2017-07-27 16:23
@jschlieber Thanks for issue, confirmed. Let's wait what says @TrySound (he have access for `postcss-*` plugins for `css-loader`)

**Comment by jschlieber** [comment] 2017-08-10 08:39
@evilebottnawi Thanks for your efforts. Any news on this one?

**Comment by evilebottnawi** [comment] 2017-08-10 10:14
@jschlieber no :disappointed: 
@TrySound friendly ping

**Comment by TrySound** [comment] 2017-08-10 20:26
I guess it's something in selector tokenizer. Patch release will help. However I don't have access yet.

**Comment by TrySound** [comment] 2017-08-10 20:26
https://github.com/css-modules/css-selector-tokenizer

**Comment by 6palace** [comment] 2018-01-19 19:30
+1 from us as well

**Comment by RoopGuron** [comment] 2018-01-19 19:33
+1 This fix is needed.

**Comment by EvanLovely** [comment] 2018-02-07 00:11
I've got a workaround [detailed here](https://github.com/bolt-design-system/bolt/pull/410)

**Comment by EvanLovely** [comment] 2018-02-07 19:22
I found where this is being caused: [`./lib/getLocalIndent.js` has a `.replace()` function](https://github.com/webpack-contrib/css-loader/blob/630579d01e9d28a2032e707dcea2ad9f4ec613da/lib/getLocalIdent.js#L15:73) that replaces a big RegEx with `-` (if you change that character and run you can see it being used).

**Comment by EvanLovely** [comment] 2018-02-07 19:42
It appears that by the time it hits this file, classes like `.u-hide\@large` are already `.u-hide@large`, and then after that line become ``.u-hide-large`.

**Comment by EvanLovely** [comment] 2018-02-07 19:52
Hmm... also turning CSS modules off with `options.modules = false` "fixes" it.

**Comment by evilebottnawi** [comment] 2018-02-15 14:48
Just infromation:
```css
.icon-caret-left:before {
   content: '"\\f10c"'
}
```

Also broken

**Comment by evilebottnawi** [comment] 2018-02-15 14:56
Also
```css
body {
  font-family: '微软雅黑'; /* some chinese font name */
}
```

**Comment by martin-minovski** [comment] 2018-03-24 23:54
+1

**Comment by themoch** [comment] 2018-04-09 19:40
I'm having a slightly different issue.

Loader
```
{
          loader: "css-loader",
          options: {
            sourceMap: true,
            camelCase: "dashes",
            importLoaders: 1,
            modules: true,
            localIdentName: "[name]__[local]___[hash:base64:5]"
          }
        },
```

input.css
```
.myStyle {
    content: '\e901';
}
```

transforms to:

output.css
```
styles__myStyle___1LKpi {
    content: '\E901';
}
```

☝️ notice the uppercasing of `E`.  This breaks the unicode used in the font icon

**Comment by pitgrap** [comment] 2018-10-24 13:36
Another similar bug:

input.css
```
.glyphicon-search:before {
  content: "\e003 \fe0e";
}
```

output.css

```
.glyphicon-search:before {
  content: "\E003   \FE0E";
}
```

1. Transform to uppercase like @themoch described
2. Instead of one space there are now 3 spaces between the characters!

**Comment by jihb** [comment] 2018-11-07 04:13
> Another similar bug:
> 
> input.css
> 
> ```
> .glyphicon-search:before {
>   content: "\e003 \fe0e";
> }
> ```
> output.css
> 
> ```
> .glyphicon-search:before {
>   content: "\E003   \FE0E";
> }
> ```
> 1. Transform to uppercase like @themoch described
> 2. Instead of one space there are now 3 spaces between the characters!

same problem.

**Comment by jihb** [comment] 2018-11-07 04:16
> > Another similar bug:
> > input.css
> > ```
> > .glyphicon-search:before {
> >   content: "\e003 \fe0e";
> > }
> > ```
> > output.css
> > ```
> > .glyphicon-search:before {
> >   content: "\E003   \FE0E";
> > }
> > ```
> > 
> > 1. Transform to uppercase like @themoch described
> > 2. Instead of one space there are now 3 spaces between the characters!
> 
> same problem.

delete space fix this problem

**Comment by evilebottnawi** [comment] 2018-12-05 22:01
All fixed in master exclude selectors, it is very hard, workaround use `.u-m\+` instead `.u-m\00002b`

**Comment by dulakm** [comment] 2019-01-18 11:16
Hello,
please, is there any update on the issue? I can confirm another problem with escaping similar to the one mentioned in https://github.com/webpack-contrib/css-loader/issues/752.

When using CSS modules and `@custom-selector` plugin, even the most basic example escaping goes wrong:
```
@custom-selector :--heading h1, h2, h3;
article :--heading + p {
    margin-top: 0;
}
```
=>
```
@custom-selector :--heading h1, h2, h3;
article :\--heading + p {
    margin-top: 0;
}
```

**Comment by evilebottnawi** [comment] 2019-01-18 11:18
@dulakm problem in css modules plugins (for postcss), feel free investigate and send a PR

**Comment by Lynn-cc** [comment] 2019-01-24 04:12
my base64 image：`data:img/jpg;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAAXNSR0IArs4c6QAAAhxJREFUSA3tk71rU1EYxnMTEoJUkowWwdJ2akEHBfGjCiIF6ZylVUKSm2TqZLGI+A/oIu2UXm8C4lAyF4SWji0tdFLo1Eo7VN0SaBEhH7e/Nz0nPTfGOjiaCyfPc5734zlfCQT6X/8E/vUErL81KBaL9y3LSnued5PcITjUOwR3gsFg2bbtjYt6/NGgXC4P1et1l2aPLmpAbD0SidjpdPqgV15PA9d17zQajU8UxHQRK/4G35Q5pveAK8LlI1ZjPMnlcltnyvnvbwaO41xvtVqy7YHztMACq5xnlb9EY3dRdvcGo1kj5wR+t1AofDG0gM+A875E8DNjRCexsrV8Pj9ZqVQitVrtqejxePxjMpmss5hVTB4buXvMb2DyU2tBTRS+BjvNlVYUpPl7iuVO3Gq1uoQx1FtSOW1gPgp5ZWrdBtNmUDgv5asgxQ8F1af5vhY0YjyjuWC3wTszKJz7GBOkcFlQfW2ONq4FjWi+Hj6DRCKxQOK2TlY4x92EuYd5dvMAbYIzfikau3pu5tJ8KxaLLfo0cyKci7tK4TZjUMcoXAmHwzle0Q/RaC5P1GFMyVx9R9Fo9HYqlTrSgqDvFelAqVQa5hmuMR/WGtjAaBdjwBoDQ0ZsnwVMZjKZ9n0Zem8DSeDPdrnZbL6F2l3NOvUYNZk4oVDoRTabPe4EDNJzB0ZcjAYxeoZ2i3FNxQ7BHYw/cB/fldaH//UETgHHO8S44KbfXgAAAABJRU5ErkJggg==`

escaped to：
`data:img/jpg;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAAXNSR0IArs4c6QAAAhxJREFUSA3tk71rU1EYxnMTEoJUkowWwdJ2akEHBfGjCiIF6ZylVUKSm2TqZLGI+A/oIu2UXm8C4lAyF4SWji0tdFLo1Eo7VN0SaBEhH7e/Nz0nPTfGOjiaCyfPc5734zlfCQT6X/8E/vUErL81KBaL9y3LSnued5PcITjUOwR3gsFg2bbtjYt6/NGgXC4P1et1l2aPLmpAbD0SidjpdPqgV15PA9d17zQajU8UxHQRK/4G35Q5pveAK8LlI1ZjPMnlcltnyvnvbwaO41xvtVqy7YHztMACq5xnlb9EY3dRdvcGo1kj5wR+t1AofDG0gM+A875E8DNjRCexsrV8Pj9ZqVQitVrtqejxePxjMpmss5hVTB4buXvMb2DyU2tBTRS+BjvNlVYUpPl7iuVO3Gq1uoQx1FtSOW1gPgp5ZWrdBtNmUDgv5asgxQ8F1af5vhY0YjyjuWC3wTszKJz7GBOkcFlQfW2ONq4FjWi+Hj6DRCKxQOK2TlY4x92EuYd5dvMAbYIzfikau3pu5tJ8KxaLLfo0cyKci7tK4TZjUMcoXAmHwzle0Q/RaC5P1GFMyVx9R9Fo9HYqlTrSgqDvFelAqVQa5hmuMR/WGtjAaBdjwBoDQ0ZsnwVMZjKZ9n0Zem8DSeDPdrnZbL6F2l3NOvUYNZk4oVDoRTabPe4EDNJzB0ZcjAYxeoZ2i3FNxQ7BHYw/cB/fldaH/UETgHHO8S44KbfXgAAAABJRU5ErkJggg==`

notice the `//U` in the last line，was escaped to `/U`, and it's broken.

**Comment by evilebottnawi** [comment] 2019-01-24 09:44
@Lynn-cc can't reproduce (https://github.com/webpack-contrib/css-loader/pull/888), see snapshots, maybe you use old version of `css-loader`?

**Closed** 2019-03-05 11:50 UTC
Labels: priority: 3 (required), semver: Patch, severity: 3 (broken), type: Bug
