### ISSUE TITLE
Font urls does not work when using sourceMap

### ISSUE THREAD

**Issue by hoanguyen311** [webpack-contrib/css-loader#296] opened 2016-07-03 10:45 UTC
webpack configuration:

``` javascript
modules: {
    loaders: [{
        test: /\.scss$/,
        loader: ['style', 'css?sourceMap', 'postcss',
            'sass?sourceMap'
        ].join('!')
    }, {
        test: /\.(mp4|ogg|svg|eot|ttf|woff|woff2|jpg|png)$/,
        loader: 'file-loader'
    }]
}
```

**styles/fonts.scss**

``` sass
@font-face {
  font-family : "foundation-icons";
  font-style  : normal;
  font-weight : normal;
  src         : url(foundation-icons.eot);
  src         : url(foundation-icons.eot?#iefix) format("embedded-opentype"),
                url(foundation-icons.woff) format("woff"),
                url(foundation-icons.ttf) format("truetype"),
                url(foundation-icons.svg#fontcustom) format("svg");
}
```

And the font icons doesn't work
<img width="144" alt="screen shot 2016-07-03 at 17 45 28" src="https://cloud.githubusercontent.com/assets/5975761/16545004/f7c4f7aa-4145-11e6-81a4-e874eea29eb6.png">

It's ok after I removed `sourceMap` option of css-loader
<img width="725" alt="screen shot 2016-07-03 at 17 47 26" src="https://cloud.githubusercontent.com/assets/5975761/16545021/45e576d0-4146-11e6-9f63-324adc81450c.png">

**Comment by acidicX** [comment] 2016-07-07 14:38
duplicate of https://github.com/webpack/css-loader/issues/232 I think

**Comment by blowsie** [comment] 2016-08-15 14:35
Only difference which this ticket is the source is sass and not css

**Comment by evilebottnawi** [comment] 2017-05-26 16:20
@hoanguyen311 Error still exists?

**Comment by janvesel** [comment] 2017-05-26 18:37
Yes I have same issue.

**Comment by evilebottnawi** [comment] 2017-05-26 19:55
@janvesel your use webpack v1?

**Comment by janvesel** [comment] 2017-05-26 21:39
@evilebottnawi I use webpack v1.14

**Comment by evilebottnawi** [comment] 2017-05-27 10:53
@janvesel can your upgrade config to v2 and tests again?

**Comment by Kaijun** [comment] 2017-07-06 07:41
@evilebottnawi webpack 2/3 doesn't work either.

**Comment by evilebottnawi** [comment] 2017-07-06 11:38
@Kaijun can your create minimum reproducible test repo?

**Comment by evilebottnawi** [comment] 2018-02-15 13:29
Closing due to inactivity. Please test with latest version and feel free to reopen if still regressions. Thanks!

**Closed by evilebottnawi** 2018-02-15 13:29 UTC

**Comment by EstevesDiogo** [comment] 2019-02-10 01:38
I still have that problem, any solution?

**Comment by janvesel** [comment] 2019-02-11 08:30
@EstevesDiogo I created a workaround by adding another loader for file that load fonts only and for that I didn't use sourceMap and I excluded the font.css file from the scss loader that uses sourceMap.

```
{
    test    : /\.scss$/,
    loader  : isBuild ? ExtractTextPlugin.extract(['css-loader', 'postcss-loader', 'sass-loader']) : 'style-loader!css-loader?sourceMap!postcss-loader?sourceMap!sass-loader?sourceMap',
    include : [path-to-assets],
    exclude : [`path-to-assets/fonts.scss`]
  },
{
    test    : /\.css$/,
    loader  : isBuild ? ExtractTextPlugin.extract(['css-loader', 'postcss-loader', 'sass-loader']) : 'style-loader!css-loader!sass-loader',
    include : [`path-to-assets/fonts.css`]
  },
```
