### ISSUE TITLE
___CSS_LOADER_GET_URL_IMPORT___ is not a function

### ISSUE THREAD

**Issue by cgb1021** [webpack-contrib/css-loader#1096] opened 2020-06-24 07:05 UTC
- Operating System: windows 10
- Node Version: 12.17.0
- NPM Version: 6.14.4
- webpack Version: 4.43.0
- css-loader Version: 3.6.0

### Code
First,in the scss file,I set a background image.It can load the image correct.
```js
@include background('#{$img}/inline/btn_sure.png');
```
Second,delete the background image.
```js
// @include background('#{$img}/inline/btn_sure.png');
```
Then,recover the background image.It can't load the image.
```js
@include background('#{$img}/inline/btn_sure.png');
```
In chrome Console,it report:
```js
bootstrap:457 [HMR] unexpected require(../common/img/mobile/pop/inline/btn_sure.png) to disposed module
TypeError: ___CSS_LOADER_GET_URL_IMPORT___ is not a function
```
Chrome debug info:
![企业微信截图_15929924228073](https://user-images.githubusercontent.com/3213767/85534338-da509680-b643-11ea-9bdd-40f37715a71d.png)

**Comment by evilebottnawi** [comment] 2020-06-24 12:08
It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

Please do not ignore fields in the issue template, I can't reproduce

**Closed by evilebottnawi** 2020-06-24 12:08 UTC
