### ISSUE TITLE
Module build failed: Syntax Error (5:1) Unknown word

### ISSUE THREAD

**Issue by yinshipeng** [webpack-contrib/css-loader#617] opened 2017-09-29 11:50 UTC
ERROR in ./~/css-loader!./~/sass-loader/lib/loader.js!./~/postcss-loader/lib!./~/extract-text-webpack-plugin/loader.js?{"omit":1,"remove":true}!./~/vue-style-loader!./~/css-loader?{"minimize":true,"sourceMap":true}!./src/assets/css/index.css
Module build failed: Syntax Error 

(5:1) Unknown word

  3 | // load the styles
  4 | var content = require("!!../../../node_modules/css-loader/index.js?{\"minimize\":true,\"sourceMap\":true}!./index.css");
> 5 | if(typeof content === 'string') content = [[module.id, content, '']];
    | ^
  6 | if(content.locals) module.exports = content.locals;
  7 | // add the styles to the DOM

 @ ./src/assets/css/index.css 4:14-348
 @ ./src/main.js

**Comment by evilebottnawi** [comment] 2017-09-29 12:03
@yinshipeng seems you have invalid configuration, please provide your `webpack` configuration, thank you!

**Comment by yinshipeng** [comment] 2017-09-29 12:11
I just configured the CSS - loader, the file with the suffix called CSS.
`{
            test  : /\.css$/,
            loader: 'css-loader'
        }`

**Comment by yinshipeng** [comment] 2017-09-29 12:15
`ERROR in ./src/assets/css/index.css
Module build failed: Unknown word (5:1)

  3 | // load the styles
  4 | var content = require("!!../../../node_modules/css-loader/index.js??ref--6-2!./index.css");
  5 | if(typeof content === 'string') content = [[module.id, content, '']];
    | ^
  6 | if(content.locals) module.exports = content.locals;
  7 | // add the styles to the DOM
  8 | var update = require("!../../../node_modules/vue-style-loader/lib/addStylesClient.js")("b58619c0", content, true);

 @ ./src/main.js 8:0-32
`

I import './ assets/CSS/index.css 'in main.js file, only in the index.css file `body{
    font-size: 12px;
}`

**Comment by evilebottnawi** [comment] 2017-09-29 12:18
@yinshipeng you need `style-loader` for `css` if you want to import in `js`

**Comment by yinshipeng** [comment] 2017-09-29 12:41
`{
            test: /\.css$/,
            loader:  ExtractTextPlugin.extract({ fallback: 'style-loader', use: 'css-loader' })
        }
`
`new ExtractTextPlugin({
        filename: utils.assetsPath('css/[name].[contenthash].css')
    })`

The same mistakes will be made~

**Comment by evilebottnawi** [comment] 2017-09-29 13:20
@yinshipeng please provide full webpack configuration or minimum reproducible test repo, thanks!

**Comment by mkMoSs** [comment] 2017-10-19 16:46
I have the exact same issue
``` 
Module build failed: Unknown word (5:1)

  3 | // load the styles
  4 | var content = require("!!../../../css-loader/index.js?{\"modules\":true,\"sourceMap\":true,\"importLoaders\":1,\"localIdentName\":\"[name]--[local]--[hash:base64:8]\"}!../../../postcss-loader/lib/index.js!./theme.css");
> 5 | if(typeof content === 'string') content = [[module.id, content, '']];
    | ^
  6 | // Prepare cssTransformation
  7 | var transform;
  8 |
```

Here's my webpack config (3.5.0 is used) through laravel-mix:

```
       module: {
           rules: [
               {
                   test: /\.css$/,
                   use: [
                       { loader: "style-loader" },
                       {
                           loader: "css-loader",
                           options: {
                               modules: true, // default is false
                               sourceMap: true,
                               importLoaders: 1,
                               localIdentName: "[name]--[local]--[hash:base64:8]",
                           },
                       },
                       { loader: "postcss-loader" },
                   ],
               },
           ],
```

package.json dependencies:
```
    "devDependencies": {
        "babel-preset-es2015": "^6.24.1",
        "babel-preset-react": "^6.24.1",
        "babel-preset-stage-0": "^6.24.1",
        "browser-sync": "^2.18.13",
        "browser-sync-webpack-plugin": "^1.2.0",
        "cross-env": "^5.0.5",
        "css-loader": "^0.28.7",
        "laravel-mix": "1.4.5",
        "postcss-loader": "^2.0.8",
        "style-loader": "^0.19.0"
    },
    "dependencies": {
        "postcss": "^6.0.13",
        "postcss-cssnext": "^3.0.2",
        "react": "^16.0.0",
        "react-dom": "^16.0.0",
        "react-router": "^4.2.0",
        "react-router-dom": "^4.2.2",
        "react-scripts": "1.0.14",
        "react-toolbox": "^2.0.0-beta.12"
    }

```

I'm trying to use react-toolbox (Material UI components) which requires postcss and I'm unable to make it work. I have no clue where the issue lies, however it seems it's a problem with either css-loader or style-loader.

**Comment by evilebottnawi** [comment] 2017-10-20 09:33
@mkMoSs create minimum reproducible test repo, thank you

**Comment by mkMoSs** [comment] 2017-10-20 19:08
@evilebottnawi I have created a minimal repo that reproduces the bug.
https://github.com/mkMoSs/css-loader-bug

**Comment by xywai1993** [comment] 2017-11-03 06:06
I have the same problem。Very helpless。

webpack.prod.js

`module:{
        rules: [
            {
                 test: /\.css$/,
                 use: ExtractTextPlugin.extract({
                    fallback: "style-loader",
                     use: "css-loader"
                 })
          
             }
        ]
    },
    plugins: [
        new CleanWebpackPlugin(['dist']),
        new webpack.DefinePlugin({
            'process.env': {
                NODE_ENV: JSON.stringify('production')
            }
        }),
        new webpack.optimize.UglifyJsPlugin({
            compress: {
                warnings: false,
                drop_console: true
            },
            sourceMap: true
        }),
         new ExtractTextPlugin({
             filename: path.posix.join('', 'css/[name].css')
        }),
        new OptimizeCSSPlugin()
    ]
`

**Comment by Dygerati** [comment] 2017-11-03 22:04
Same issue here, tried a few different config's to no avail. 

Console output:
```ERROR in ./node_modules/css-loader!./web-root/style.css
Module build failed: Unknown word (5:1)

  3 | // load the styles
  4 | var content = require("!!../node_modules/css-loader/index.js!./style.css");
> 5 | if(typeof content === 'string') content = [[module.id, content, '']];
    | ^
  6 | // Prepare cssTransformation
  7 | var transform;
  8 | 

 @ ./scripts/index.js 13:0-43
```

webpack.config.js
```
const path = require('path');

module.exports = {
   entry: './scripts/index.js',
   output: {
      filename: 'code.js',
      path: path.resolve(__dirname, 'static')
   },
   devServer: {
      contentBase: './static'
   },
   module: {
      rules: [
         {
            test: /\.css$/,
            use: [ 'style-loader', 'css-loader' ]
         },
         {
            test: /\.js$/,
            exclude: /(node_modules|bower_components)/,
            use: {
               loader: 'babel-loader',
               options: {
                  presets: [ '@babel/preset-env', '@babel/preset-react' ]
               }
            }
         }
      ]
   }
};
```
And the include:
```
import 'css-loader!../web-root/style.css';
```

In package.json:
```
  "devDependencies": {
    "@babel/core": "^7.0.0-beta.5",
    "@babel/preset-env": "^7.0.0-beta.5",
    "@babel/preset-react": "^7.0.0-beta.4",
    "babel-loader": "8.0.0-beta.0",
    "css-loader": "^0.28.7",
    "style-loader": "^0.19.0",
    "eslint-plugin-react": "^7.4.0",
    "webpack": "^3.8.1",
    "webpack-dev-server": "^2.9.4"
  }
```

**Comment by michael-ciniawsky** [comment] 2017-11-03 22:17
@Dygerati 

```diff
- import 'css-loader!../web-root/style.css';
+ import '../web-root/style.css';
```

**Comment by Dygerati** [comment] 2017-11-03 23:41
Thanks @michael-ciniawsky, although I tried that as well and just get a different error: 

```
ERROR in ./web-root/images/bg.png
Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
 @ ./node_modules/css-loader!./web-root/style.css 6:64-90
 @ ./web-root/style.css
 @ ./scripts/index.js

```

**Comment by michael-ciniawsky** [comment] 2017-11-03 23:47
You need setup a loader for images

```js
{
   test: /\.(png|jpg|gif)$/,
   use: [ 'file-loader' ]
}
```

or disable asset resolving in `css-loader`  via `options.url = false`

**Comment by Dygerati** [comment] 2017-11-03 23:54
Welp, that did it. Looks like I got lazy and didn't read the error in detail. Thanks!

**Comment by xywai1993** [comment] 2017-11-06 17:36
hello, @evilebottnawi  , The following case will present this problem 
`npm run build`

https://github.com/xywai1993/demo/tree/master/webpack%E5%AD%A6%E4%B9%A0

**Comment by gaponenkodv** [comment] 2017-11-20 10:35
I have a similar problem
` ERROR in ./node_modules/css-loader!./ClientApp/scripts/scss/material.scss
    Module build failed: Unknown word (530:29)

      528 |
      529 |     @each $key, $val in $colors {
    > 530 |         &:checked.chk-col-#{$key} {
               |                                          ^
      531 |             + label {
      532 |                 &:before {
      533 |                     border-right: 2px solid $val;`

webpack
`rules: [
                {
                    test: /\.ts$/, include: /ClientApp/, use: isDevBuild ? [{
                        loader: 'ng-router-loader',
                        options: {
                            loader: 'async-import',
                            genDir: 'compiled',
                            aot: !isDevBuild
                        }
                    }, 'awesome-typescript-loader?silent=true', 'angular2-template-loader']
                        : '@ngtools/webpack'
                },
                { test: /\.html$/, use: 'html-loader?minimize=false' },
                { test: /\.css$/, use: ['to-string-loader', isDevBuild ? 'css-loader' : 'css-loader?minimize'] },
                { test: /\.scss$/, use: ['to-string-loader' ,'css-loader', 'sass-loader']},
                { test: /\.(jpg|png|gif)$/, use: 'file-loader' },
                { test: /\.(woff|woff2|eot|ttf|svg)$/, use: 'file-loader' }
            ]`
why? could somebody help me?

**Comment by xu-oliver** [comment] 2017-11-24 03:28
a similar problem ! Has anybody finish ?


`ERROR in ./node_modules/css-loader!./public/stylesheets/style.css
Module build failed: Unknown word (1:1)

> 1 | exports = module.exports = require("../../node_modules/css-loader/lib/css-base.js")(undefined);
    | ^
  2 | // imports
  3 |
  4 |

 @ ./public/js/entry.js 2:0-46
 @ multi public/js/entry.js ./public/js/entry.js bundle.js`

**Comment by xu-oliver** [comment] 2017-11-24 03:31
Just only css-loader , this css-loader & style-loader

`ERROR in ./node_modules/css-loader!./node_modules/style-loader!./node_modules/css-loader!./public/stylesheets/style.css
Module build failed: Unknown word (5:1)

  3 | // load the styles
  4 | var content = require("!!../../node_modules/css-loader/index.js!./style.css");
> 5 | if(typeof content === 'string') content = [[module.id, content, '']];
    | ^
  6 | // Prepare cssTransformation
  7 | var transform;
  8 |

 @ ./node_modules/style-loader!./node_modules/css-loader!./public/stylesheets/style.css 4:14-157
 @ ./public/js/entry.js
 @ multi public/js/entry.js ./public/js/entry.js bundle.js`

**Closed** 2018-01-08 05:41 UTC

**Comment by amrshakya** [comment] 2018-03-07 14:27
can anyone help me out. i'm using extract-text-webpack-plugin

webpack.config.js
const path = require('path');
const ExtractTextPlugin = require('extract-text-webpack-plugin');

var extractPlugin = new ExtractTextPlugin({
    filename: 'main.css'
});

module.exports = {
    entry: './src/js/app.js',
    output: {
        path: path.resolve(__dirname, 'dist'),
        filename: 'bundle.js',
        publicPath: '/dist'
    },
    module: {
        rules: [
            {
                test: /\.js$/,
                use: [
                    {
                        loader: 'babel-loader',
                        options: {
                            presets: ['es2015']
                        }
                    }
                ]
            },
            {
                test: /\.scss$/,
                use: extractPlugin.extract({
                    fallback: 'style-loader',
                    use: ['css-loader', 'sass-loader']
                })
            }
        ]
    },
    plugins: [
        extractPlugin
    ]
}

getting this error:
ERROR in ./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./src/css/main.scss
Module build failed:
@import "colors";
^
      File to import not found or unreadable: colors.
Parent style sheet: stdin
      in /Users/amarshakya/Documents/Amr/jsProject/webpack-demo/src/css/main.scss (line 1, column 1)
 @ ./src/css/main.scss 2:14-122
 @ ./src/js/app.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/js/app.js

ERROR in ./src/css/main.scss
Module build failed: ModuleBuildError: Module build failed:
@import "colors";
^
      File to import not found or unreadable: colors.
Parent style sheet: stdin
      in /Users/amarshakya/Documents/Amr/jsProject/webpack-demo/src/css/main.scss (line 1, column 1)
    at runLoaders (/Users/amarshakya/Documents/Amr/jsProject/webpack-demo/node_modules/webpack/lib/NormalModule.js:195:19)
    at /Users/amarshakya/Documents/Amr/jsProject/webpack-demo/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /Users/amarshakya/Documents/Amr/jsProject/webpack-demo/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/Users/amarshakya/Documents/Amr/jsProject/webpack-demo/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.asyncSassJobQueue.push [as callback] (/Users/amarshakya/Documents/Amr/jsProject/webpack-demo/node_modules/sass-loader/lib/loader.js:55:13)
    at Object.done [as callback] (/Users/amarshakya/Documents/Amr/jsProject/webpack-demo/node_modules/neo-async/async.js:7921:18)
    at options.error (/Users/amarshakya/Documents/Amr/jsProject/webpack-demo/node_modules/node-sass/lib/index.js:294:32)
 @ ./src/css/main.scss
 @ ./src/js/app.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/js/app.js
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js!node_modules/sass-loader/lib/loader.js!src/css/main.scss:
       [0] ./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./src/css/main.scss 249 bytes {0} [built] [failed] [1 error]

    ERROR in ./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./src/css/main.scss
    Module build failed:
    @import "colors";
    ^
          File to import not found or unreadable: colors.
    Parent style sheet: stdin
          in /Users/amarshakya/Documents/Amr/jsProject/webpack-demo/src/css/main.scss (line 1, column 1)
webpack: Failed to compile.

**Comment by gaoshu883** [comment] 2018-03-14 07:47
I also encountered the similar question when using extract-text-webpack-plugin to extract multiple css files:
```bash
    (1:1) Unknown word
    > 1 | exports = module.exports = require("../../../css-loader/lib/css-base.js")(true);
        | ^
      2 | // imports
      3 |
```
Finally, I have found that I extract the same css content with two ExtractTextPlugin instances. My solution is as follow:

In my case, I import many css files:
```JavaScript
    import './css/main.css'
    import './css/base.css'
    import './css/other.css'
```
I only want to extract the `base.css` and others build into a single one file.

Then the webpack config may look as follow:
```JavaScript
  const ExtractTextPlugin = require('extract-text-webpack-plugin')
  const extractApp = new ExtractTextPlugin('static/css/app.[contenthash].css')
  const extractBase = new ExtractTextPlugin('static/css/common.[contenthash].css')
  module.exports = {
  // other config ...
    module: {
      rules: [{
         test: /\.css$/,
         exclude: /base\.css$/,  // important, you cannot include this css file
         use: extractApp(['css-loader', 'postcss-loader'])
      }, {
         test: /base\.css$/,
         use: extractBase(['css-loader', 'postcss-loader'])
      }]
    },
    plugins: [
        extractBase,    // instance
        extractApp     // instance
    ]
｝
````

**Comment by Ramnath24** [comment] 2018-04-11 10:04
ERROR in ./~/css-loader?{"minimize":true}!./~/sass-loader/lib/loader.js!./src/styles/_master.scss
Module build failed: Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\B0074907\Desktop\Projects\3.0.0-R2\cobas-e-library-frontend\node_modules\sass-loader\lib\loader.js:3:14)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at loadLoader (C:\Users\B0074907\Desktop\Projects\3.0.0-R2\cobas-e-library-frontend\node_modules\loader-runner\lib\loadLoader.js:13:17)
    at iteratePitchingLoaders (C:\Users\B0074907\Desktop\Projects\3.0.0-R2\cobas-e-library-frontend\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at iteratePitchingLoaders (C:\Users\B0074907\Desktop\Projects\3.0.0-R2\cobas-e-library-frontend\node_modules\loader-runner\lib\LoaderRunner.js:165:10)
    at C:\Users\B0074907\Desktop\Projects\3.0.0-R2\cobas-e-library-frontend\node_modules\loader-runner\lib\LoaderRunner.js:173:18
    at loadLoader (C:\Users\B0074907\Desktop\Projects\3.0.0-R2\cobas-e-library-frontend\node_modules\loader-runner\lib\loadLoader.js:36:3)
    at iteratePitchingLoaders (C:\Users\B0074907\Desktop\Projects\3.0.0-R2\cobas-e-library-frontend\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at runLoaders (C:\Users\B0074907\Desktop\Projects\3.0.0-R2\cobas-e-library-frontend\node_modules\loader-runner\lib\LoaderRunner.js:362:2)
    at NormalModule.doBuild (C:\Users\B0074907\Desktop\Projects\3.0.0-R2\cobas-e-library-frontend\node_modules\webpack\lib\NormalModule.js:179:3)
    at NormalModule.build (C:\Users\B0074907\Desktop\Projects\3.0.0-R2\cobas-e-library-frontend\node_modules\webpack\lib\NormalModule.js:268:15)
    at Compilation.buildModule (C:\Users\B0074907\Desktop\Projects\3.0.0-R2\cobas-e-library-frontend\node_modules\webpack\lib\Compilation.js:146:10)
 @ ./src/styles/_master.scss 4:14-135
 @ ./src/app/app.component.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi (webpack)-dev-server/client?http://localhost:8088 ./src/main.ts

ERROR in ./src/styles/_master.scss
Module build failed: ModuleBuildError: Module build failed: Error: Cannot find module 'node-sass'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\B0074907\Desktop\Projects\3.0.0-R2\cobas-e-library-frontend\node_modules\sass-loader\lib\loader.js:3:14)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at loadLoader (C:\Users\B0074907\Desktop\Projects\3.0.0-R2\cobas-e-library-frontend\node_modules\loader-runner\lib\loadLoader.js:13:17)
    at iteratePitchingLoaders (C:\Users\B0074907\Desktop\Projects\3.0.0-R2\cobas-e-library-frontend\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at iteratePitchingLoaders (C:\Users\B0074907\Desktop\Projects\3.0.0-R2\cobas-e-library-frontend\node_modules\loader-runner\lib\LoaderRunner.js:165:10)
    at C:\Users\B0074907\Desktop\Projects\3.0.0-R2\cobas-e-library-frontend\node_modules\loader-runner\lib\LoaderRunner.js:173:18
    at loadLoader (C:\Users\B0074907\Desktop\Projects\3.0.0-R2\cobas-e-library-frontend\node_modules\loader-runner\lib\loadLoader.js:36:3)
    at iteratePitchingLoaders (C:\Users\B0074907\Desktop\Projects\3.0.0-R2\cobas-e-library-frontend\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at runLoaders (C:\Users\B0074907\Desktop\Projects\3.0.0-R2\cobas-e-library-frontend\node_modules\loader-runner\lib\LoaderRunner.js:362:2)
    at NormalModule.doBuild (C:\Users\B0074907\Desktop\Projects\3.0.0-R2\cobas-e-library-frontend\node_modules\webpack\lib\NormalModule.js:179:3)
    at NormalModule.build (C:\Users\B0074907\Desktop\Projects\3.0.0-R2\cobas-e-library-frontend\node_modules\webpack\lib\NormalModule.js:268:15)
    at Compilation.buildModule (C:\Users\B0074907\Desktop\Projects\3.0.0-R2\cobas-e-library-frontend\node_modules\webpack\lib\Compilation.js:146:10)
    at runLoaders (C:\Users\B0074907\Desktop\Projects\3.0.0-R2\cobas-e-library-frontend\node_modules\webpack\lib\NormalModule.js:192:19)
    at C:\Users\B0074907\Desktop\Projects\3.0.0-R2\cobas-e-library-frontend\node_modules\loader-runner\lib\LoaderRunner.js:364:11
    at C:\Users\B0074907\Desktop\Projects\3.0.0-R2\cobas-e-library-frontend\node_modules\loader-runner\lib\LoaderRunner.js:170:18
    at loadLoader (C:\Users\B0074907\Desktop\Projects\3.0.0-R2\cobas-e-library-frontend\node_modules\loader-runner\lib\loadLoader.js:27:11)
    at iteratePitchingLoaders (C:\Users\B0074907\Desktop\Projects\3.0.0-R2\cobas-e-library-frontend\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at iteratePitchingLoaders (C:\Users\B0074907\Desktop\Projects\3.0.0-R2\cobas-e-library-frontend\node_modules\loader-runner\lib\LoaderRunner.js:165:10)
    at C:\Users\B0074907\Desktop\Projects\3.0.0-R2\cobas-e-library-frontend\node_modules\loader-runner\lib\LoaderRunner.js:173:18
    at loadLoader (C:\Users\B0074907\Desktop\Projects\3.0.0-R2\cobas-e-library-frontend\node_modules\loader-runner\lib\loadLoader.js:36:3)
    at iteratePitchingLoaders (C:\Users\B0074907\Desktop\Projects\3.0.0-R2\cobas-e-library-frontend\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at runLoaders (C:\Users\B0074907\Desktop\Projects\3.0.0-R2\cobas-e-library-frontend\node_modules\loader-runner\lib\LoaderRunner.js:362:2)
    at NormalModule.doBuild (C:\Users\B0074907\Desktop\Projects\3.0.0-R2\cobas-e-library-frontend\node_modules\webpack\lib\NormalModule.js:179:3)
    at NormalModule.build (C:\Users\B0074907\Desktop\Projects\3.0.0-R2\cobas-e-library-frontend\node_modules\webpack\lib\NormalModule.js:268:15)
    at Compilation.buildModule (C:\Users\B0074907\Desktop\Projects\3.0.0-R2\cobas-e-library-frontend\node_modules\webpack\lib\Compilation.js:146:10)
    at moduleFactory.create (C:\Users\B0074907\Desktop\Projects\3.0.0-R2\cobas-e-library-frontend\node_modules\webpack\lib\Compilation.js:433:9)
    at factory (C:\Users\B0074907\Desktop\Projects\3.0.0-R2\cobas-e-library-frontend\node_modules\webpack\lib\NormalModuleFactory.js:253:5)
    at applyPluginsAsyncWaterfall (C:\Users\B0074907\Desktop\Projects\3.0.0-R2\cobas-e-library-frontend\node_modules\webpack\lib\NormalModuleFactory.js:99:14)
    at C:\Users\B0074907\Desktop\Projects\3.0.0-R2\cobas-e-library-frontend\node_modules\tapable\lib\Tapable.js:268:11
    at NormalModuleFactory.params.normalModuleFactory.plugin (C:\Users\B0074907\Desktop\Projects\3.0.0-R2\cobas-e-library-frontend\node_modules\webpack\lib\CompatibilityPlugin.js:52:5)
    at NormalModuleFactory.applyPluginsAsyncWaterfall (C:\Users\B0074907\Desktop\Projects\3.0.0-R2\cobas-e-library-frontend\node_modules\tapable\lib\Tapable.js:272:13)
    at resolver (C:\Users\B0074907\Desktop\Projects\3.0.0-R2\cobas-e-library-frontend\node_modules\webpack\lib\NormalModuleFactory.js:74:11)
    at process.nextTick (C:\Users\B0074907\Desktop\Projects\3.0.0-R2\cobas-e-library-frontend\node_modules\webpack\lib\NormalModuleFactory.js:205:8)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)

ERROR in C:\Users\B0074907\Desktop\Projects\3.0.0-R2\cobas-e-library-frontend\node_modules\extract-text-webpack-plugin\loader.js??ref--3-0!C:\Users\B0074907\Desktop\Projects\3.0.0-R2\cobas-e-library-frontend\node_modules\style-loader\index.js!C:\Users\B0074907\Desktop\Projects\3.0.0-R2\cobas-e-library-frontend\node_modules\css-loader\index.js??ref--3-2!C:\Users\B0074907\Desktop\Projects\3.0.0-R2\cobas-e-library-frontend\node_modules\sass-loader\lib\loader.js!C:\Users\B0074907\Desktop\Projects\3.0.0-R2\cobas-e-library-frontend\src\styles\_master.scss doesn't export content
Child html-webpack-plugin for "index.html":
    chunk    {0} index.html 327 bytes [entry] [rendered]
Child extract-text-webpack-plugin:
    chunk    {0} extract-text-webpack-plugin-output-filename 2.3 kB [entry] [rendered]

    ERROR in ./~/css-loader?{"minimize":true}!./~/sass-loader/lib/loader.js!./src/styles/_master.scss
    Module build failed: Error: Cannot find module 'node-sass'
        at Function.Module._resolveFilename (module.js:547:15)
        at Function.Module._load (module.js:474:25)
        at Module.require (module.js:596:17)
        at require (internal/module.js:11:18)
        at Object.<anonymous> (C:\Users\B0074907\Desktop\Projects\3.0.0-R2\cobas-e-library-frontend\node_modules\sass-loader\lib\loader.js:3:14)
        at Module._compile (module.js:652:30)
        at Object.Module._extensions..js (module.js:663:10)
        at Module.load (module.js:565:32)
        at tryModuleLoad (module.js:505:12)
        at Function.Module._load (module.js:497:3)
        at Module.require (module.js:596:17)
        at require (internal/module.js:11:18)
        at loadLoader (C:\Users\B0074907\Desktop\Projects\3.0.0-R2\cobas-e-library-frontend\node_modules\loader-runner\lib\loadLoader.js:13:17)
        at iteratePitchingLoaders (C:\Users\B0074907\Desktop\Projects\3.0.0-R2\cobas-e-library-frontend\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
        at iteratePitchingLoaders (C:\Users\B0074907\Desktop\Projects\3.0.0-R2\cobas-e-library-frontend\node_modules\loader-runner\lib\LoaderRunner.js:165:10)
        at C:\Users\B0074907\Desktop\Projects\3.0.0-R2\cobas-e-library-frontend\node_modules\loader-runner\lib\LoaderRunner.js:173:18
        at loadLoader (C:\Users\B0074907\Desktop\Projects\3.0.0-R2\cobas-e-library-frontend\node_modules\loader-runner\lib\loadLoader.js:36:3)
        at iteratePitchingLoaders (C:\Users\B0074907\Desktop\Projects\3.0.0-R2\cobas-e-library-frontend\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
        at runLoaders (C:\Users\B0074907\Desktop\Projects\3.0.0-R2\cobas-e-library-frontend\node_modules\loader-runner\lib\LoaderRunner.js:362:2)
        at NormalModule.doBuild (C:\Users\B0074907\Desktop\Projects\3.0.0-R2\cobas-e-library-frontend\node_modules\webpack\lib\NormalModule.js:179:3)
        at NormalModule.build (C:\Users\B0074907\Desktop\Projects\3.0.0-R2\cobas-e-library-frontend\node_modules\webpack\lib\NormalModule.js:268:15)
        at Compilation.buildModule (C:\Users\B0074907\Desktop\Projects\3.0.0-R2\cobas-e-library-frontend\node_modules\webpack\lib\Compilation.js:146:10)
webpack: Failed to compile.



can any one help me out from this error. I'm new to node js

**Comment by WuJiangquan** [comment] 2018-06-11 04:02
try this:
npm install --save-dev node-sass

**Comment by armw4** [comment] 2019-02-12 22:04
I encountered this when using the `MiniCssExtractPlugin`. The setup for the documentation helped me. I had consolidated my `.css` and `.scss` blocks as follows:

<img width="933" alt="screen shot 2019-02-12 at 16 03 20" src="https://user-images.githubusercontent.com/246377/52671129-e10fbb00-2edf-11e9-82ef-468722dc36c4.png">

**Comment by Shhuy** [comment] 2019-05-25 07:30
Perhaps it's the sequence of calls to css-loader and style-loader, which should be handled by calling css-loader first.

**Comment by kazinoman** [comment] 2020-04-01 14:25
I face an error. here it is , please help me.

ERROR in Module build failed (from ./node_modules/postcss-loader/src/index.js):
SyntaxError

(1:1) Unknown word

> 1 | .
      | ^
  2  |

**Comment by dm-bishnoi** [comment] 2020-08-11 12:11
**I Face the same issue
**
