### ISSUE TITLE
Avoid hash collisions by default with random hashPrefix?

### ISSUE THREAD

**Issue by claudiorodriguez** [webpack-contrib/css-loader#413] opened 2017-01-27 14:43 UTC
Hey everyone, just sharing a problem I found, to see if I'm missing something or if the suggested improvement could be a good idea.

If you go with the default options, or define your own `localIdentName`, the generated `hash`, without a `hashPrefix`, will be a digest of the relative path and the local classname.
This causes collision when you have two separate modules built with webpack that have a file with the same path, with the same classname in it (both modules have `src/blah/styles.scss` with the class `.classname` in it)
To solve this collision, I added a `hashPrefix` to the `query`, making it random on each build (something like `<package-name> + Date.now()` works great).
Isn't it a good idea to make a random `hashPrefix` be default behaviour?

**Comment by AdamJo** [comment] 2017-02-03 03:24
Running into the same issue. Any advice would be much appreciated.

**Comment by jeffijoe** [comment] 2017-02-26 15:56
@claudiorodriguez do you have an example for your solution? Running into this as well.

**Comment by claudiorodriguez** [comment] 2017-02-28 14:53
@AdamJo @jeffijoe the easiest workaround is to add `hashPrefix` to your `css-loader` `query`, e.g.
```
{
  loader: 'css-loader',
  query: {
    hashPrefix: 'package-name' + Date.now()
    localIdentName: [local]_[hash:base64:5],
    modules: true
  }
}
```

**Comment by jeffijoe** [comment] 2017-02-28 14:55
@claudiorodriguez oh okay! I was looking through docs to see if I could find any `hashPrefix` variable anywhere but I couldn't - isn't this documented?

**Comment by claudiorodriguez** [comment] 2017-02-28 15:10
I think it's undocumented. It's used here https://github.com/webpack-contrib/css-loader/blob/master/lib/getLocalIdent.js#L12

**Comment by jeffijoe** [comment] 2017-02-28 15:10
Damn, I looked at that file for like 10 minutes and I didn't spot that - @claudiorodriguez thank you!

**Comment by mitkaaa** [comment] 2017-03-03 12:48
If you are use LoaderOptionsPlugin, then you can add context
```
new webpack.LoaderOptionsPlugin({
                options: {
                    context: __dirname,
...
```
classes will be unique

**Comment by plrthink** [comment] 2017-03-22 15:45
@mitkaaa thanks, this works for me. but could you please explain why this would solve this issue?

**Comment by dcworldwide** [comment] 2017-04-17 07:09
Agree @mitkaaa i'm a bit confused by the solution... is this global config or local to css loader?

**Comment by jacobwalton** [comment] 2017-05-04 16:22
I think you can set `context` to `__dirname` on the `options` object passed in to css-loader, you shouldn't need to use LoaderOptionsPlugin.

@plrthink @dcworldwide I believe this works because css-loader uses the value of `options.context` when generating the hash used in the `localIdentName`. By default `context` is just the local directory name of the module but by setting it to `__dirname` it includes the full absolute system path to that module, e.g. '/Users/bob/example' instead of just 'example', resulting in a different hash each time.

**Comment by jeffijoe** [comment] 2017-05-04 16:27
Won't `__dirname` just set it to the path of the webpack config?

**Comment by jacobwalton** [comment] 2017-05-04 16:40
Yeah, you're right. Seems to work anyway. ¯\_(ツ)_/¯  Will try and dig into it further at some point.

**Comment by mrchief** [comment] 2017-05-05 20:26
`__dirname` is not resolved when webpack loads. Its tucked away in a lazy function (`getLocalIdent`) that gets evaluated when a css file is bring processed. So it'll point to correct path everytime.

**Comment by jeffijoe** [comment] 2017-05-05 20:33
If you specify `context: __dirname` in your webpack config, then it _should_ be evaluated when webpack loads: https://nodejs.org/docs/latest/api/globals.html#globals_dirname

**Comment by jacobwalton** [comment] 2017-05-05 21:18
`__dirnane` is set In webpack config to the config's file path but `getLocalIdent` then resolves the relative path from the there to the stylesheet, thereby generating a unique string for each for use in the hashing algorithm.

**Comment by jeffijoe** [comment] 2017-05-05 21:20
Ah, I see. My bad.

**Comment by anhdn** [comment] 2017-06-20 09:28
@mitkaaa you saved me!

**Comment by evilebottnawi** [comment] 2018-02-15 13:26
Feel free to documentation this!

**Comment by qrew** [comment] 2018-02-19 01:28
Got same problem after moving to webpack-4.0.0beta. Updating css-loader with context fix this issue for me too. Config example:

`{ loader: 'css-loader',
          options: {
            modules: true,
            context: __dirname,
            localIdentName: '[local]-[hash:base64:6]',
        }`

Thanks so much for this solution!

**Comment by user1736** [comment] 2018-09-17 15:20
I've opened a PR to refer this problem and workaround in docs https://github.com/webpack-contrib/css-loader/pull/770

**Comment by evilebottnawi** [comment] 2018-12-05 16:08
Somebody can create minimum reproducible test repo?

**Comment by evilebottnawi** [comment] 2019-03-05 16:07
Closing due impossible reproduce. Feel free to create new issue if you faced with problem. Thanks!

**Closed by evilebottnawi** 2019-03-05 16:07 UTC
Labels: priority: 5 (nice to have), semver: Patch, severity: 4 (inconvenient), type: Documentation
