### ISSUE TITLE
css modules reduces bundle size

### ISSUE THREAD

**Issue by Kashio** [webpack-contrib/css-loader#970] opened 2019-07-16 21:20 UTC
Hey I'm trying to reduce my css bundle size by using css modules with the following `localIdentName`:

`localIdentName: '[sha1:hash:hex:4]'`

Problem is that I see an increased size in my css bundle by 8kb and 40kb in my sourcemap for that bundle.

I was wondering if I might be doing something wrong or falling into a css module gotcha that I might have been missing?

Would appreciate any help thanks!

**Comment by evilebottnawi** [comment] 2019-07-17 09:49
It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

Without reproducible test repo/examples i can't say what is wrong, also in some cases css modules can increase bundle size

**Closed by evilebottnawi** 2019-07-17 09:49 UTC
