### ISSUE TITLE
JS file size increases 291 kB -> 314 kB upon upgrading from v0.25.0 to v0.28.0

### ISSUE THREAD

**Issue by elfey** [webpack-contrib/css-loader#476] opened 2017-04-06 19:29 UTC
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**
For some reason upon upgrading to v0.28.0 of css-loader from v0.25.0, our project's build size increased from 291 kB to 314 kB. This doesn't make sense... why is a loader for CSS increasing our JS build size when we're exporting it to CSS?

**If the current behavior is a bug, please provide the steps to reproduce.**

Take any JavaScript project, and build with both versions of css loader (v0.25.0 and v0.28.0)

**What is the expected behavior?**
It shouldn't touch the JS, we're exporting it to a separate file.

**Please mention other relevant information such as your webpack version, Node.js version and Operating System.**
Webpack 2.2.0
Tested on Node 6.9.10 and 7.7.3
Mac OS 10.12.4

**Comment by michael-ciniawsky** [comment] 2017-04-06 19:38
Duplicate of #454

**Closed by michael-ciniawsky** 2017-04-06 19:38 UTC
